# Generated by Django 4.0.8 on 2023-09-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verificated_email_emailverification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='expriration',
            new_name='expiration',
        ),
    ]
